name: linkedin_login
description: Library for login with LinkedIn OAuth V2 service with OpedID. This library helps you to implement authorization with LinkedIn OAuth API's.

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  meta: ^1.11.0
  rxdart: ^0.27.7
  uuid: ^4.3.3
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  mockito: ^5.4.4
  test: ^1.24.9
  flutter_lints: ^3.0.1

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/linked_in_logo.png
